server:
  port: 8081

spring:
  application:
    name: gateway-marcadopago
  cloud:
    gateway:
      routes:
        - id: get_token
          uri: http://localhost:8080/test
          predicates:
            - Path=/**
            - TokenCapture=test
          filters:

